version: "3.4"

services:
  roboeyes:
    build: .
    image: ethanjahn/roboeyes:1.0.0
    container_name: roboeyes
    network_mode: "host"
    tty: true
    environment:
      - "DISPLAY=${DISPLAY}"
      - ARDUINO_IDE_VERSION=1.8.13
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "${HOME}/topics:/topics"
    privileged: true
    command: bash
